Updating TODO and README files...

diff --git a/scripts/uninstall b/scripts/uninstall
--- a/scripts/uninstall
+++ b/scripts/uninstall
@@ -3,7 +3,7 @@
 # OPEW uninstaller
 # @description This utility script 
 # @license GNU GPL 3.0
-# @version Beta - 03/02/2012
+# @version Beta - 04/02/2012
 #
 
 # check if run as root
@@ -13,6 +13,15 @@ if [ "`id -u`" -ne 0 ]; then
        exit 1
 fi
 
+# check PATH environment variable
+if [ -z $PATH ]; then
+	echo "The PATH environment variable is empty. Cannot continue with the installation process..."
+	echo "Must be defined in order to run the installer properly. "
+	echo "Please, copy and ejecute this (or your customized PATH environment): " 
+	echo 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
+	exit 1
+fi
+
 echo "##################################"
 echo "        OPEW uninstaller "
 echo "##################################"
@@ -20,6 +29,7 @@ echo " "
 read -p "Do you want to uninstall OPEW from this system? (y|N): " response
 case $response in
 	y|Y|yes|Yes|YES)
+		echo " "
 		echo "Stating unintall process..."
 	;;
  	*)
